apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-52pw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-52pw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-52pw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-52pw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-52pw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ejoz-tenant/rhtap-demo-app/hacbs-test-project-52pw@sha256:405df032084b6d4765260aa1e332cccf9a438d0293633a247c3829278373ddc7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
